bda/urls.py
from django.conf.urls import url

from bda import views
from bda.views import SpectacleListView
from gestioncof.decorators import buro_required

urlpatterns = [
    url(
        r"^inscription/(?P<tirage_id>\d+)$",
        views.inscription,
        name="bda-tirage-inscription",
    ),
    url(r"^places/(?P<tirage_id>\d+)$", views.places, name="bda-places-attribuees"),
    url(r"^etat-places/(?P<tirage_id>\d+)$", views.etat_places, name="bda-etat-places"),
    url(r"^tirage/(?P<tirage_id>\d+)$", views.tirage, name="bda-tirage"),
    url(
        r"^spectacles/(?P<tirage_id>\d+)$",
        buro_required(SpectacleListView.as_view()),
        name="bda-liste-spectacles",
    ),
    url(
        r"^spectacles/(?P<tirage_id>\d+)/(?P<spectacle_id>\d+)$",
        views.spectacle,
        name="bda-spectacle",
    ),
    url(
        r"^spectacles/unpaid/(?P<tirage_id>\d+)$",
        views.UnpaidParticipants.as_view(),
        name="bda-unpaid",
    ),
    url(
        r"^spectacles/autocomplete$",
        views.spectacle_autocomplete,
        name="bda-spectacle-autocomplete",
    ),
    url(
        r"^participants/autocomplete$",
        views.participant_autocomplete,
        name="bda-participant-autocomplete",
    ),
    # Urls BdA-Revente
    url(
        r"^revente/(?P<tirage_id>\d+)/manage$",
        views.revente_manage,
        name="bda-revente-manage",
    ),
    url(
        r"^revente/(?P<tirage_id>\d+)/subscribe$",
        views.revente_subscribe,
        name="bda-revente-subscribe",
    ),
    url(
        r"^revente/(?P<tirage_id>\d+)/tirages$",
        views.revente_tirages,
        name="bda-revente-tirages",
    ),
    url(
        r"^revente/(?P<spectacle_id>\d+)/buy$",
        views.revente_buy,
        name="bda-revente-buy",
    ),
    url(
        r"^revente/(?P<revente_id>\d+)/confirm$",
        views.revente_confirm,
        name="bda-revente-confirm",
    ),
    url(
        r"^revente/(?P<tirage_id>\d+)/shotgun$",
        views.revente_shotgun,
        name="bda-revente-shotgun",
    ),
    url(r"^mails-rappel/(?P<spectacle_id>\d+)$", views.send_rappel, name="bda-rappels"),
    url(r"^catalogue/(?P<request_type>[a-z]+)$", views.catalogue, name="bda-catalogue"),
]

bds/urls.py
from django.urls import path

from bds import views

app_name = "bds"
urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("autocomplete", views.BDSAutocompleteView.as_view(), name="autocomplete"),
    path("user/update/<int:pk>", views.UserUpdateView.as_view(), name="user.update"),
    path("user/create/", views.UserCreateView.as_view(), name="user.create"),
    path(
        "user/create/<slug:clipper>",
        views.UserCreateView.as_view(),
        name="user.create.fromclipper",
    ),
    path("user/delete/<int:pk>", views.UserDeleteView.as_view(), name="user.delete"),
    path("members", views.export_members, name="export.members"),
    path(
        "members/expired",
        views.ResetMembershipListView.as_view(),
        name="members.expired",
    ),
    path("members/reset", views.ResetMembershipView.as_view(), name="members.reset"),
]

bds/models.py
from datetime import date
from os.path import splitext

from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from shared.utils import choices_length

User = get_user_model()


class BDSProfile(models.Model):
    OCCUPATION_CHOICES = (
        ("EXT", "Extérieur"),
        ("1A", "1A"),
        ("2A", "2A"),
        ("3A", "3A"),
        ("4A", "4A"),
        ("MAG", "Magistérien"),
        ("ARC", "Archicube"),
        ("DOC", "Doctorant"),
        ("CST", "CST"),
        ("PER", "Personnel ENS"),
    )

    TYPE_COTIZ_CHOICES = (
        ("ETU", "Étudiant"),
        ("NOR", "Normalien"),
        ("EXT", "Extérieur"),
        ("ARC", "Archicube"),
    )

    COTIZ_DURATION_CHOICES = (
        ("ANN", "Année"),
        ("SE1", "Premier semestre"),
        ("SE2", "Deuxième semestre"),
        ("NO", "Aucune"),
    )

    def get_certificate_filename(instance, filename):
        _, ext = splitext(filename)  # récupère l'extension du fichier
        year = str(date.now().year)
        return "certifs/{username}-{year}.{ext}".format(
            username=instance.user.username, year=year, ext=ext
        )

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="bds")
    phone = models.CharField(_("téléphone"), max_length=20, blank=True)
    occupation = models.CharField(
        _("occupation"),
        default="1A",
        choices=OCCUPATION_CHOICES,
        max_length=choices_length(OCCUPATION_CHOICES),
    )
    departement = models.CharField(_("département"), max_length=50, blank=True)
    birthdate = models.DateField(
        auto_now_add=False,
        auto_now=False,
        verbose_name=_("date de naissance"),
        blank=True,
        null=True,
    )

    is_member = models.BooleanField(_("adhérent⋅e du BDS"), default=False)

    mails_bds = models.BooleanField(_("recevoir les mails du BDS"), default=False)

    has_certificate = models.BooleanField(_("certificat médical"), default=False)

    ASPSL_number = models.CharField(
        _("numéro AS PSL"), max_length=50, blank=True, null=True
    )
    FFSU_number = models.CharField(
        _("numéro FFSU"), max_length=50, blank=True, null=True
    )
    cotisation_period = models.CharField(
        _("inscription"), default="NO", choices=COTIZ_DURATION_CHOICES, max_length=3
    )
    registration_date = models.DateField(
        auto_now_add=True, verbose_name=_("date d'inscription")
    )
    cotisation_type = models.CharField(
        _("type de cotisation"), choices=TYPE_COTIZ_CHOICES, max_length=9
    )

    comments = models.TextField(
        _("commentaires"),
        blank=True,
        help_text=_(
            "Attention : l'utilisateur·ice dispose d'un droit d'accès aux données "
            "le/la concernant, dont le contenu de ce champ !"
        ),
    )

    @classmethod
    def expired_members(cls):
        now = timezone.now()
        qs = cls.objects.filter(is_member=True)
        if now.month > 1 and now.month < 7:
            return qs.filter(cotisation_period="SE1")
        elif now.month < 2 or now.month > 8:
            return qs.none()
        return qs

    class Meta:
        verbose_name = _("Profil BDS")
        verbose_name_plural = _("Profils BDS")
        permissions = (("is_team", _("est membre du burô")),)

    def __str__(self):
        return self.user.username

bds/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

from bds.models import BDSProfile

User = get_user_model()


class UserForm(forms.ModelForm):
    is_buro = forms.BooleanField(label=_("Membre du Burô"), required=False)

    class Meta:
        model = User
        fields = ["email", "first_name", "last_name"]


class UserFromClipperForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].disabled = True

    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]


class UserFromScratchForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = BDSProfile
        exclude = ["user"]
        widgets = {
            "birthdate": forms.DateInput(attrs={"type": "date"}, format="%Y-%m-%d")
        }

bds/views.py
import csv

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import Permission
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import DeleteView, ListView, RedirectView, TemplateView

from bds.autocomplete import bds_search
from bds.forms import ProfileForm, UserForm, UserFromClipperForm, UserFromScratchForm
from bds.mixins import MultipleFormView, StaffRequiredMixin
from bds.models import BDSProfile
from shared.views import AutocompleteView

User = get_user_model()


class BDSAutocompleteView(StaffRequiredMixin, AutocompleteView):
    template_name = "bds/search_results.html"
    search_composer = bds_search


class Home(StaffRequiredMixin, TemplateView):
    template_name = "bds/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["member_count"] = BDSProfile.objects.filter(is_member=True).count()
        context["nb_expired"] = BDSProfile.expired_members().count()
        return context


class UserUpdateView(StaffRequiredMixin, MultipleFormView):
    template_name = "bds/user_update.html"

    form_classes = {
        "user": UserForm,
        "profile": ProfileForm,
    }

    def get_user_initial(self):
        return {"is_buro": self.get_user_instance().has_perm("bds.is_team")}

    def dispatch(self, request, *args, **kwargs):
        self.user = get_object_or_404(User, pk=self.kwargs["pk"])
        return super().dispatch(request, *args, **kwargs)

    def get_user_instance(self):
        return self.user

    def get_profile_instance(self):
        return getattr(self.user, "bds", None)

    def get_success_url(self):
        return reverse("bds:user.update", args=(self.user.pk,))

    def form_valid(self, forms):
        user = forms["user"].save()
        profile = forms["profile"].save(commit=False)
        perm = Permission.objects.get(content_type__app_label="bds", codename="is_team")
        if forms["user"].cleaned_data["is_buro"]:
            user.user_permissions.add(perm)
        else:
            user.user_permissions.remove(perm)
        profile.user = user
        profile.save()
        messages.success(self.request, _("Profil mis à jour avec succès !"))

        return super().form_valid(forms)

    def form_invalid(self, forms):
        messages.error(self.request, _("Veuillez corriger les erreurs ci-dessous"))
        return super().form_invalid(forms)


class UserCreateView(StaffRequiredMixin, MultipleFormView):
    template_name = "bds/user_create.html"

    def get_form_classes(self):
        profile_class = ProfileForm

        if "clipper" in self.kwargs:
            user_class = UserFromClipperForm
        else:
            user_class = UserFromScratchForm

        return {"user": user_class, "profile": profile_class}

    def get_user_initial(self):
        if "clipper" in self.kwargs:
            clipper = self.kwargs["clipper"]
            email = self.request.GET.get("mail", "{}@clipper.ens.fr".format(clipper))
            fullname = self.request.GET.get("fullname", None)

            if fullname:
                # Heuristique : le premier mot est le prénom
                first_name = fullname.split()[0]
                last_name = " ".join(fullname.split()[1:])
            else:
                first_name = ""
                last_name = ""

            return {
                "username": clipper,
                "email": email,
                "first_name": first_name,
                "last_name": last_name,
            }
        else:
            return {}

    def get_success_url(self):
        return reverse("bds:user.update", args=(self.user.pk,))

    def form_valid(self, forms):
        # On redéfinit self.user pour get_success_url
        self.user = forms["user"].save()
        profile = forms["profile"].save(commit=False)
        profile.user = self.user
        profile.save()
        messages.success(self.request, _("Profil créé avec succès !"))

        return super().form_valid(forms)

    def form_invalid(self, forms):
        messages.error(self.request, _("Veuillez corriger les erreurs ci-dessous"))
        return super().form_invalid(forms)


class UserDeleteView(StaffRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy("bds:home")
    success_message = "Profil supprimé avec succès !"

    def delete(self, request, *args, **kwargs):
        # SuccessMessageMixin does not work with DeleteView, see :
        # https://code.djangoproject.com/ticket/21926
        messages.success(request, self.success_message)

        return super().delete(request, *args, **kwargs)


class ResetMembershipListView(StaffRequiredMixin, ListView):
    model = BDSProfile
    template_name = "bds/expired_members.html"

    def get_queryset(self):
        return BDSProfile.expired_members()


class ResetMembershipView(StaffRequiredMixin, RedirectView):
    url = reverse_lazy("bds:members.expired")

    def get(self, request, *args, **kwargs):
        qs = BDSProfile.expired_members()
        nb = qs.count()

        qs.update(cotisation_period="NO", is_member=False, mails_bds=False)

        messages.success(request, f"{nb} adhésions réinitialisées")

        return super().get(request, *args, **kwargs)


@permission_required("bds.is_team")
def export_members(request):
    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = "attachment; filename=membres_bds.csv"

    writer = csv.writer(response)
    for profile in BDSProfile.objects.filter(is_member=True).all():
        user = profile.user
        bits = [
            user.username,
            user.get_full_name(),
            user.email,
        ]
        writer.writerow([str(bit) for bit in bits])

    return response

bds/templates/bds/base.html
{% load staticfiles %}
{% load bulma_utils %}

<!DOCTYPE html>
<html>
  <head>
    <title>{{ site.name }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {# CSS #}
    <link rel="stylesheet" href="{% static "bds/css/bds.css" %}">
    <link type="text/css" rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">

    {# Javascript #}
    <script src="{% static 'vendor/jquery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static "vendor/jquery/jquery.autocomplete-light.min.js" %}"></script>
    <script src="{% static 'bds/js/bds.js' %}"></script>

    {% block extra_head %}{% endblock extra_head %}
  </head>
  <body>
    {% include "bds/nav.html" %}
    {% block layout %}
    <div class="columns">
      <div class="column is-two-thirds is-offset-2">
        <section class="section">

          {% if messages %}
            {% for message in messages %}
              <div class="notification is-{{ message.level_tag|bulma_message_tag }}">
                {% if 'safe' in message.tags %}
                    {{ message|safe }}
                {% else %}
                    {{ message }}
                {% endif %}
                <button class="delete"></button>
              </div>
            {% endfor %}
          {% endif %}

          {% block content %}
          {% endblock content %}
        </section>
      </div>
    </div>
    {% endblock layout %}
  </body>
</html>

bds/templates/bds/expired_members.html
{% extends "bds/base.html" %}


{% block content %}

<h1 class="title">Liste des adhésions expirées</h1>

{% if object_list %}
<div class="content">
    <ul>
        {% for p in object_list %}
        <li>{{ p.user.first_name }} {{ p.user.last_name }} ({{ p.user.username }}), {{ p.get_cotisation_period_display }}</li>
        {% endfor %}
    </ul>
</div>

<div class="buttons is-centered">
  <a class="button is-danger" href="{% url 'bds:members.reset' %}">Réinitialiser les adhésions expirées</a>
</div>
{% endif %}

{% endblock %}

bds/templates/bds/home.html
{% extends "bds/base.html" %}
{% load bulma_utils %}

{% block layout %}
<div class="columns">
  <div class="column is-2">
    <section class="section">
      <div class="box">
        <div class="content has-text-centered">
          <h1>{{ member_count }}</h1>
          adhérent·e·s
        </div>
      </div>
    </section>
  </div>
  <div class="column is-two-thirds">
    <section class="section">

      {% if messages %}
        {% for message in messages %}
          <div class="notification is-{{ message.level_tag|bulma_message_tag }}">
            {% if 'safe' in message.tags %}
                {{ message|safe }}
            {% else %}
                {{ message }}
            {% endif %}
            <button class="delete"></button>
          </div>
        {% endfor %}
      {% endif %}
      <div class="container">
        Bienvenue sur GestioBDS&#8239;!

        <br>
        <br>

        <a class=button href="{% url 'bds:export.members' %}">Télécharger la liste des membres (CSV)</a>

        <a class=button href="{% url 'bds:members.expired' %}">Liste des adhésions expirées ({{ nb_expired }})</a>

        <br>
        <br>

        Le site est encore en développement.
        <br>
        Suivez notre avancement sur
        <a href="https://git.eleves.ens.fr/klub-dev-ens/gestioCOF/merge_requests?milestone_title=Int%C3%A9gration+du+BDS">
        cette milestone</a> sur le gitlab de l'ENS.
        <br>
        Faites vos remarques par mail à
        <a href="mailto:klub-dev@ens.fr"><tt>klub-dev@ens.fr</tt></a>
        ou en ouvrant une
        <a href="#https://git.eleves.ens.fr/klub-dev-ens/gestioCOF/issues?milestone_title=Int%C3%A9gration+du+BDS">
        issue</a>.
      </div>
    </section>
  </div>
</div>
{% endblock layout %}

bds/templates/bds/nav.html
{% load i18n %}
{% load static %}

<nav id="search-bar" class="level">
  <div class="level-item" id="logo">
    <figure class="image is-64x64">
      <a href="{% url "bds:home" %}">
        <img src="{% static "bds/images/logo_square.svg" %}" alt="bds-logo">
      </a>
    </figure>
  </div>

  <div class="level-item" id="logout-mobile">
    <figure class="image is-64x64">
      <a href="{% url 'authens:logout' %}">
        <img src="{% static "bds/images/logout.svg" %}" alt="logout">
      </a>
    </figure>
  </div>

  <div class="level-item" id="search-input">
    <input
      class="input"
      type="text"
      name="q"
      id="search_autocomplete"
      spellcheck="false"
      placeholder="{% trans "Chercher une personne" %}" />
    <div class="yourlabs-autocomplete"></div>
  </div>

  <div class="level-item" id="logout">
    <figure class="image is-64x64">
      <a href="{% url 'authens:logout' %}">
        <img src="{% static "bds/images/logout.svg" %}" alt="logout">
      </a>
    </figure>
  </div>
</nav>

<script type="text/javascript">
  $(document).ready(function() {
    $('input#search_autocomplete').yourlabsAutocomplete({
      url: '{% url 'bds:autocomplete' %}',
      minimumCharacters: 3,
      id: 'search_autocomplete',
      choiceSelector: 'li:has(a)',
      box: $(".yourlabs-autocomplete"),
    });
    $('input#search_autocomplete').bind(
      'selectChoice',
      function(e, choice, autocomplete) {
        window.location = choice.find('a:first').attr('href');
      }
    );
  });
</script>

bds/templates/bds/search_results.html
{% extends "shared/search_results.html" %}
{% load i18n %}

{% block extra_section %}
  <li class="autocomplete-header">
    {% if not results %}
      <span class="autocomplete-item">
        {% trans "Aucune correspondance trouvée" %}
      </span>
    {% else %}
      <span class="autocomplete-item">
        {% trans "Pas dans la liste ?" %}
      </span>
    {% endif %}
  </li>
  <li class="autocomplete-new">
    <a class="autocomplete-item" href="{% url "bds:user.create" %}">
      {% trans "Créer un compte" %}
    </a>
  </li>
{% endblock %}

bds/templates/bds/user_create.html
{% extends "bds/base.html" %}
{% load i18n %}


{% block content %}

{% for form in forms.values %}
  {% for error in form.non_field_errors %}
    <div class="notification is-danger">
      {{ error }}
    </div>
  {% endfor %}
{% endfor %}

<h1 class="title">{% trans "Création d'un profil" %}</h1>

<div class="container">
  <form action="" method="post">
    {% csrf_token %}

    {% for form in forms.values %}
      {% include "bds/forms/form.html" with form=form errors=False %}
    {% endfor %}

    <div class="field">
      <p class="control">
        <input class="button is-fullwidth" type="submit" value="Enregistrer">
      </p>
    </div>
  </form>
</div>

{% endblock %}

bds/templates/bds/user_update.html
{% extends "bds/base.html" %}
{% load i18n %}


{% block content %}

{% for form in forms.values %}
{% for error in form.non_field_errors %}
<div class="notification is-danger">
    {{ error }}
</div>
{% endfor %}
{% endfor %}

<h1 class="title">{% trans "Modification du profil " %}{{ view.user.username }}</h1>

<div class="container">
    <form method="post" action="" id="user-update-form">
        {% csrf_token %}

        {% for form in forms.values %}
        {% include "bds/forms/form.html" with form=form errors=False %}
        {% endfor %}
    </form>

    <form method="post" action="{% url 'bds:user.delete' view.user.pk %}" id="user-delete-form">
        {% csrf_token %}
    </form>

    <div class="columns is-gapless mt-5">
        <div class="column is-5">
            <button id="user-update-button" class="button is-fullwidth is-primary">Enregistrer</button>
        </div>
        <div class="column is-2">
        </div>
        <div class="column is-5">
            <button id="user-delete-button" class="button is-fullwidth is-danger">Supprimer</button>
        </div>
    </div>
</div>

<!-- Hidden by default -->
<div id="confirm-delete-modal" class="modal">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Confirmer la suppression</p>
            <button id="modal-close" class="delete" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
            Voulez-vous réellement supprimer ce compte ? Attention, cette opération est irréversible !
        </section>
        <footer class="modal-card-foot">
            <button id="confirm-delete-button" class="button is-primary">Supprimer</button>
            <button id="cancel-delete-button" class="button">Annuler</button>
        </footer>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        "use strict";

        // Adapted from https://bulma.io/lib/main.js
        function openModal(target) {
            $(document).addClass('is-clipped');
            $(`#${target}`).addClass('is-active');
        }

        function closeModals() {
            $(document).removeClass('is-clipped');
            $(".modal").removeClass('is-active');
        }

        // Si on clique sur enregistrer, ça marche
        $("#user-update-button").on("click", function() {
            $("#user-update-form").submit();
        })

        // Si on clique sur supprimer, confirmation demandée
        $("#user-delete-button").on("click", function() {
            openModal("confirm-delete-modal");
        });

        $(".modal-background, #modal-close, #cancel-delete-button").on("click", closeModals);

        $("#confirm-delete-button").on("click", function() {
            $("#user-delete-form").submit();
        });

        $(document).on("keydown", function(e) {
            if (e.key == "Escape") {
                closeModals();
            }

            if (e.key == "Enter") {
                $("#user-update-form").submit();
            }
        });

    });
</script>

{% endblock %}